name: Nightly Builds
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Build
        run: go build -v ./...

      - name: Package
        run: bash build-all.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Prebuilt binaries
          path: dist.tar.gz
